In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [10]:
df=pd.read_csv('GlobalWeatherRepository.csv')

In [11]:
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [12]:
df.shape

(124721, 41)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124721 entries, 0 to 124720
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       124721 non-null  object
 1   location_name                 124721 non-null  object
 2   latitude                      124721 non-null  float64
 3   longitude                     124721 non-null  float64
 4   timezone                      124721 non-null  object
 5   last_updated_epoch            124721 non-null  int64
 6   last_updated                  124721 non-null  object
 7   temperature_celsius           124721 non-null  float64
 8   temperature_fahrenheit        124721 non-null  float64
 9   condition_text                124721 non-null  object
 10  wind_mph                      124721 non-null  float64
 11  wind_kph                      124721 non-null  float64
 12  wind_degree                   124721 non-null  int64
 13  wind_direction                124721 non-null  object
 14  pressure_mb                   124721 non-null  float64
 15  pressure_in                   124721 non-null  float64
 16  precip_mm                     124721 non-null  float64
 17  precip_in                     124721 non-null  float64
 18  humidity                      124721 non-null  int64
 19  cloud                         124721 non-null  int64
 20  feels_like_celsius            124721 non-null  float64
 21  feels_like_fahrenheit         124721 non-null  float64
 22  visibility_km                 124721 non-null  float64
 23  visibility_miles              124721 non-null  float64
 24  uv_index                      124721 non-null  float64
 25  gust_mph                      124721 non-null  float64
 26  gust_kph                      124721 non-null  float64
 27  air_quality_Carbon_Monoxide   124721 non-null  float64
 28  air_quality_Ozone             124721 non-null  float64
 29  air_quality_Nitrogen_dioxide  124721 non-null  float64
 30  air_quality_Sulphur_dioxide   124721 non-null  float64
 31  air_quality_PM2.5             124721 non-null  float64
 32  air_quality_PM10              124721 non-null  float64
 33  air_quality_us-epa-index      124721 non-null  int64
 34  air_quality_gb-defra-index    124721 non-null  int64
 35  sunrise                       124721 non-null  object
 36  sunset                        124721 non-null  object
 37  moonrise                      124721 non-null  object
 38  moonset                       124721 non-null  object
 39  moon_phase                    124721 non-null  object
 40  moon_illumination             124721 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 39.0+ MB

In [14]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,124721.000000,124721.000000,1.247210e+05,124721.000000,124721.000000,124721.000000,124721.000000,124721.000000,124721.000000,124721.000000,...,124721.000000,124721.000000,124721.000000,124721.000000,124721.000000,124721.000000,124721.000000,124721.000000,124721.000000,124721.000000
mean,19.193490,21.992096,1.743601e+09,21.607207,70.894723,8.069774,12.990642,169.241948,1014.053503,29.944345,...,18.313128,476.647246,58.932522,15.256413,10.680584,24.598199,49.231358,1.710057,2.633855,49.620938
std,24.425953,65.793159,1.600983e+07,9.587039,17.256526,7.371973,11.860981,103.448265,10.616979,0.313481,...,14.010257,782.702069,31.136430,24.282619,36.972602,37.853030,151.999242,0.950647,2.472296,35.042022
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.729761e+09,16.300000,61.300000,3.800000,6.100000,80.000000,1010.000000,29.830000,...,10.400000,210.900000,39.000000,1.650000,1.050000,7.100000,10.050000,1.000000,1.000000,15.000000
50%,17.250000,23.240000,1.743584e+09,24.100000,75.400000,6.900000,11.200000,162.000000,1014.000000,29.930000,...,15.500000,303.400000,56.000000,5.450000,2.450000,14.245000,20.300000,1.000000,2.000000,49.000000
75%,40.400000,50.580000,1.757492e+09,28.100000,82.600000,11.000000,17.600000,256.000000,1018.000000,30.060000,...,24.300000,473.600000,75.000000,17.760000,8.650000,28.120000,42.180000,2.000000,3.000000,84.000000
max,64.150000,179.220000,1.771311e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

In [16]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [28]:
df["last_updated"] = pd.to_datetime(df["last_updated"], errors='coerce')
print(df["last_updated"].dtype)

datetime64[ns]

In [26]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [country, location_name, latitude, longitude, timezone, last_updated_epoch, last_updated, temperature_celsius, temperature_fahrenheit, condition_text, wind_mph, wind_kph, wind_degree, wind_direction, pressure_mb, pressure_in, precip_mm, precip_in, humidity, cloud, feels_like_celsius, feels_like_fahrenheit, visibility_km, visibility_miles, uv_index, gust_mph, gust_kph, air_quality_Carbon_Monoxide, air_quality_Ozone, air_quality_Nitrogen_dioxide, air_quality_Sulphur_dioxide, air_quality_PM2.5, air_quality_PM10, air_quality_us-epa-index, air_quality_gb-defra-index, sunrise, sunset, moonrise, moonset, moon_phase, moon_illumination]
Index: []

[0 rows x 41 columns]